controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

principal:
    path: /principal
    controller: App\Controller\PrincipalController::index